default:
        target: dev
        outputs:
                dev:
                        type: bigquery
                        method: oauth
                        project: starry-hawk-374910
                        dataset: dbt_zoomcamp2023                    